name: youtube_downloader
description: A Flutter app to download YouTube videos
version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  youtube_explode_dart: ^2.0.1
  file_picker: ^4.0.0
  path_provider: ^2.0.5
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  intl: ^0.17.0
flutter:
  uses-material-design: true
flutter_typeahead: ^3.1.1

